"""s

Revision ID: c245dbeb0a48
Revises: f9e0076938d7
Create Date: 2019-10-18 21:32:04.837466

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c245dbeb0a48'
down_revision = 'f9e0076938d7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Patients', sa.Column('snils_hash', sa.String(length=128), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Patients', 'snils_hash')
    # ### end Alembic commands ###
